#!/usr/bin/env ruby

# this script takes a yaml describing a merged set of benchmarks sorted by unique title
# produces puppet code with each control represented by a parameter indicating whether
# it is enabled or not
#
require 'yaml'

structure = YAML.load File.read(ARGF.file)

puts "# harden_windows_server autogenerated by os_compliance"
puts "# number of controls: #{structure.length}"

puts "class harden_windows_server ("

structure.each_pair {|title, attrs|
  puts "  Boolean $#{title} = false,"
}

puts ") {"
puts "}"

