#!/usr/bin/env ruby

# reads a benchmark file in YAML format that includes the site-specific 'enforce' boolean
# and generates the list of control titles that are to be enforced
#
# eg:
# tools/generate_enforcement_list.rb lib/cis_windows_2016rtm1607_member_server_1.1.0.yaml > enforced_controls_hiera_cis_windows_2016rtm1607_member_server_1.1.0.yaml
#
require 'yaml'

path = ARGV[0]
benchmark = File.basename(path, ".yaml")

structure = YAML.load File.read(path)
enforcees = structure.select {|control, attrs|
  attrs['enforce'] == true
}

puts "---"
puts "# cis enforcement list autogenerated by os_compliance"
puts "# for #{benchmark}"
puts "# total number of controls in benchmark: #{structure.length}"
puts "# number of controls in benchmark set to enforce: #{enforcees.length}"
puts "profile::windows::cis::enforced_controls:"

enforcees.each_pair {|control, attrs|
  puts "  - #{attrs['unique_title']} # #{control}"
}


